config/routes.rb
Rails.application.routes.draw do
  resources :lists
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list.rb
class List < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
    def index
      @lists = List.all
    end

    def new
      @list = List.new
    end

    def create
        @list = List.new(params_list)
        if @list.save
            redirect_to lists_path, notice:"新增成功"
        else
            render :new
        end
    end

    def edit
      @list = List.find_by(id: params[:id])
    end
    def update
      @list = List.find_by(id: params[:id])
      if @list.update(params_list)
        redirect_to lists_path, notice: "修改成功"  
    else
        render :edit
      end

    end

    def destroy
      @list = List.find_by(id:params[:id])
      @list.destroy if @list
      redirect_to lists_path, notice: "刪除成功"
    end


    private
    def params_list
      params.require(:list).permit(:item, :calories, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyLunchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/edit.html.erb
<h1>修改午餐</h1>

<%= link_to "返回列表", lists_path %>

<%= form_for(@list) do |form| %>
<%= form.label :item , "午餐項目" %>
<%= form.text_field :item  %>

<br>
<%= form.label :calories , "熱量" %>
<%= form.text_field :calories  %>

<br>
<%= form.label :price , "價格" %>
<%= form.text_field :price  %>

<br>

<%= form.submit %>
<% end %>

app/views/lists/index.html.erb
<h1>午餐列表</h1>

<%= flash[:notice] %>

<%= link_to "新增午餐", new_list_path %>

<table>
    <thead>
        <tr>
            <td>午餐</td>
            <td>熱量</td>
            <td>價格</td>
        </tr>
    </thead>

    <tbody>
        <% @lists.each do |list| %>
        <tr>
            <td><%= list.item %></td>
            <td><%= list.calories %></td>
            <td><%= list.price %></td>
            <td>
                <%= link_to "修改", edit_list_path(list) %>
                <%= link_to "刪除", list_path(list), method:"delete", data:{confirm:"確定刪除嗎?"} %>
            </td>
        </tr>
        <% end %>
    </tbody>
</table>

app/views/lists/new.html.erb
<h1>新增午餐</h1>

<%= link_to "返回列表", lists_path %>

<%= form_for(@list) do |form| %>
<%= form.label :item , "午餐項目" %>
<%= form.text_field :item  %>

<br>
<%= form.label :calories , "熱量" %>
<%= form.text_field :calories  %>

<br>
<%= form.label :price , "價格" %>
<%= form.text_field :price  %>

<br>

<%= form.submit %>
<% end %>